In [15]:
import numpy as np
import pandas as pd 
import os 
import html5lib
os.getcwd()

'/kaggle/working'

In [46]:
file = "https://data.cms.gov/data-api/v1/dataset/d7fabe1e-d19b-4333-9eff-e80e0643f2fd/data"
df9 = pd.read_json(file)
df9.head()

,YEAR,MONTH,BENE_GEO_LVL,BENE_STATE_ABRVTN,BENE_STATE_DESC,BENE_COUNTY_DESC,BENE_FIPS_CD,TOT_BENES,ORGNL_MDCR_BENES,MA_AND_OTH_BENES,...,AGED_NO_ESRD_BENES,DSBLD_TOT_BENES,DSBLD_ESRD_AND_ESRD_ONLY_BENES,DSBLD_NO_ESRD_BENES,A_B_TOT_BENES,A_B_ORGNL_MDCR_BENES,A_B_MA_AND_OTH_BENES,PRSCRPTN_DRUG_TOT_BENES,PRSCRPTN_DRUG_PDP_BENES,PRSCRPTN_DRUG_MAPD_BENES
0,2017,Year,National,US,National,Total,,58457244,38667830,19789414,...,49399391,8779211,258366,8520845,53008234,33242085,19766149,42728443,25243684,17484759
1,2017,Year,State,AL,Alabama,Total,01,1007423,640531,366892,...,776847,225590,5685,219905,935026,568207,366819,721687,373487,348200
2,2017,Year,County,AL,Alabama,Autauga,01001,10510,5784,4725,...,7998,2463,56,2407,9810,5085,4725,7009,2396,4613
3,2017,Year,County,AL,Alabama,Baldwin,01003,48910,28388,20522,...,41444,7320,113,7208,45818,25302,20516,34959,15298,19661
4,2017,Year,County,AL,Alabama,Barbour,01005,6275,4372,1903,...,4654,1569,54,1515,5878,3975,1903,4649,2828,1821

In [32]:
df = pd.read_csv("../input/medicare-monthly-enrollment-june-2022/Medicare_Monthly_Enrollment_June_2022.csv")
df

,YEAR,MONTH,BENE_GEO_LVL,BENE_STATE_ABRVTN,BENE_STATE_DESC,BENE_COUNTY_DESC,BENE_FIPS_CD,TOT_BENES,ORGNL_MDCR_BENES,MA_AND_OTH_BENES,...,AGED_NO_ESRD_BENES,DSBLD_TOT_BENES,DSBLD_ESRD_AND_ESRD_ONLY_BENES,DSBLD_NO_ESRD_BENES,A_B_TOT_BENES,A_B_ORGNL_MDCR_BENES,A_B_MA_AND_OTH_BENES,PRSCRPTN_DRUG_TOT_BENES,PRSCRPTN_DRUG_PDP_BENES,PRSCRPTN_DRUG_MAPD_BENES
0,2017,Year,National,US,National,Total,NaN,58457244,38667830,19789414,...,49399391,8779211,258366,8520845,53008234,33242085,19766149,42728443,25243684,17484759
1,2017,Year,State,AL,Alabama,Total,1.0,1007423,640531,366892,...,776847,225590,5685,219905,935026,568207,366819,721687,373487,348200
2,2017,Year,County,AL,Alabama,Autauga,1001.0,10510,5784,4725,...,7998,2463,56,2407,9810,5085,4725,7009,2396,4613
3,2017,Year,County,AL,Alabama,Baldwin,1003.0,48910,28388,20522,...,41444,7320,113,7208,45818,25302,20516,34959,15298,19661
4,2017,Year,County,AL,Alabama,Barbour,1005.0,6275,4372,1903,...,4654,1569,54,1515,5878,3975,1903,4649,2828,1821
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56700,2022,June,County,VI,Virgin Islands,St. John,78020.0,925,740,185,...,*,47,*,*,852,667,185,490,311,179
56701,2022,June,County,VI,Virgin Islands,St. Thomas,78030.0,9640,6628,3012,...,8916,654,51,603,8697,5685,3012,5816,2831,2985
56702,2022,June,County,VI,Virgin Islands,Unknown,78999.0,*,*,*,...,*,*,*,*,*,*,*,*,*,*
56703,2022,June,State,UK,Unknown,Unknown,99.0,*,*,*,...,*,*,*,*,*,*,*,*,*,*
56704,2022,June,State,FO,Foreign and Other Outlying Areas,Total,NaN,505399,500086,5313,...,492027,13334,23,13311,50034,44743,5291,10186,5374,4812

In [56]:
df.shape

(56705, 22)

In [57]:
df.columns

Index(['YEAR', 'MONTH', 'BENE_GEO_LVL', 'BENE_STATE_ABRVTN', 'BENE_STATE_DESC',
       'BENE_COUNTY_DESC', 'BENE_FIPS_CD', 'TOT_BENES', 'ORGNL_MDCR_BENES',
       'MA_AND_OTH_BENES', 'AGED_TOT_BENES', 'AGED_ESRD_BENES',
       'AGED_NO_ESRD_BENES', 'DSBLD_TOT_BENES',
       'DSBLD_ESRD_AND_ESRD_ONLY_BENES', 'DSBLD_NO_ESRD_BENES',
       'A_B_TOT_BENES', 'A_B_ORGNL_MDCR_BENES', 'A_B_MA_AND_OTH_BENES',
       'PRSCRPTN_DRUG_TOT_BENES', 'PRSCRPTN_DRUG_PDP_BENES',
       'PRSCRPTN_DRUG_MAPD_BENES'],
      dtype='object')

In [54]:
df.isnull()

,YEAR,MONTH,BENE_GEO_LVL,BENE_STATE_ABRVTN,BENE_STATE_DESC,BENE_COUNTY_DESC,BENE_FIPS_CD,TOT_BENES,ORGNL_MDCR_BENES,MA_AND_OTH_BENES,...,AGED_NO_ESRD_BENES,DSBLD_TOT_BENES,DSBLD_ESRD_AND_ESRD_ONLY_BENES,DSBLD_NO_ESRD_BENES,A_B_TOT_BENES,A_B_ORGNL_MDCR_BENES,A_B_MA_AND_OTH_BENES,PRSCRPTN_DRUG_TOT_BENES,PRSCRPTN_DRUG_PDP_BENES,PRSCRPTN_DRUG_MAPD_BENES
0,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56700,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
56701,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
56702,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
56703,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
56704,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [55]:
df.isnull().sum()

YEAR                               0
MONTH                              0
BENE_GEO_LVL                       0
BENE_STATE_ABRVTN                  0
BENE_STATE_DESC                    0
BENE_COUNTY_DESC                   0
BENE_FIPS_CD                      34
TOT_BENES                          0
ORGNL_MDCR_BENES                   0
MA_AND_OTH_BENES                   0
AGED_TOT_BENES                     0
AGED_ESRD_BENES                    0
AGED_NO_ESRD_BENES                 0
DSBLD_TOT_BENES                    0
DSBLD_ESRD_AND_ESRD_ONLY_BENES     0
DSBLD_NO_ESRD_BENES                0
A_B_TOT_BENES                      0
A_B_ORGNL_MDCR_BENES               0
A_B_MA_AND_OTH_BENES               0
PRSCRPTN_DRUG_TOT_BENES            0
PRSCRPTN_DRUG_PDP_BENES            0
PRSCRPTN_DRUG_MAPD_BENES           0
dtype: int64

In [58]:
df.count()

YEAR                              56705
MONTH                             56705
BENE_GEO_LVL                      56705
BENE_STATE_ABRVTN                 56705
BENE_STATE_DESC                   56705
BENE_COUNTY_DESC                  56705
BENE_FIPS_CD                      56671
TOT_BENES                         56705
ORGNL_MDCR_BENES                  56705
MA_AND_OTH_BENES                  56705
AGED_TOT_BENES                    56705
AGED_ESRD_BENES                   56705
AGED_NO_ESRD_BENES                56705
DSBLD_TOT_BENES                   56705
DSBLD_ESRD_AND_ESRD_ONLY_BENES    56705
DSBLD_NO_ESRD_BENES               56705
A_B_TOT_BENES                     56705
A_B_ORGNL_MDCR_BENES              56705
A_B_MA_AND_OTH_BENES              56705
PRSCRPTN_DRUG_TOT_BENES           56705
PRSCRPTN_DRUG_PDP_BENES           56705
PRSCRPTN_DRUG_MAPD_BENES          56705
dtype: int64

In [61]:
df['BENE_FIPS_CD'].count()

56671

In [60]:
df['BENE_FIPS_CD'].size

56705

In [50]:
df['BENE_STATE_ABRVTN']

0        US
1        AL
2        AL
3        AL
4        AL
         ..
56700    VI
56701    VI
56702    VI
56703    UK
56704    FO
Name: BENE_STATE_ABRVTN, Length: 56705, dtype: object

In [75]:
df['BENE_STATE_ABRVTN'].value_counts()

TX    4352
GA    2737
VA    2295
KY    2074
MO    1989
KS    1819
IL    1768
NC    1734
IA    1717
TN    1649
NE    1615
IN    1598
OH    1530
MN    1513
MI    1445
MS    1428
PR    1360
OK    1343
AR    1309
WI    1258
FL    1173
AL    1173
PA    1173
SD    1156
LA    1122
CO    1122
NY    1088
CA    1020
MT     986
WV     969
ND     935
SC     816
ID     782
WA     697
OR     646
NM     595
AK     539
UT     527
MD     442
WY     425
NJ     391
NV     323
ME     306
AZ     289
MA     272
VT     272
NH     204
CT     170
RI     119
HI     117
DE      85
VI      85
DC      51
UK      17
US      17
MP      17
GU      17
AS      17
FO      17
Name: BENE_STATE_ABRVTN, dtype: int64

In [76]:
df['BENE_STATE_ABRVTN'].unique()

array(['US', 'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL',
       'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD',
       'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM',
       'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN',
       'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY', 'AS', 'GU', 'MP',
       'PR', 'VI', 'UK', 'FO'], dtype=object)

In [77]:
df['BENE_STATE_ABRVTN'].nunique()

59

The number of State and Territory Abbreviations in the US is 55. That is, there are 4 data rows are errors or not exact data.
Let's delete those rows. 

I can see the 'US' in the first value of array, it contains total value. MP, UK, FO are also unkwon data. So, let's delete these 4 data from dataframe.

In [74]:
df2 = df.loc[:,['BENE_STATE_ABRVTN']]
df2

      BENE_STATE_ABRVTN
0                    US
1                    AL
2                    AL
3                    AL
4                    AL
...                 ...
56700                VI
56701                VI
56702                VI
56703                UK
56704                FO

[56705 rows x 1 columns]

In [64]:
df = df.drop(['BENE'])

AttributeError: 'Series' object has no attribute 'info'